### ISSUE TITLE
throw 'unexpected EOF'

### ISSUE THREAD

**Issue by lutzroeder** [101arrowz/fflate#18]
**Repro steps**

1. Download and unzip [fflate#18.zip](https://github.com/101arrowz/fflate/files/5721955/fflate.18.zip)
2. Download and copy [test-0001.zip](https://www.dropbox.com/s/kuapnminpyff56z/test-0001.zip?dl=0) to same folder
3. `npm install`
4. `node index.js` 

**Output**

```
~/: node index.js

~/node_modules/fflate/lib/index.js:272
                throw 'unexpected EOF';
```

**Comment by 101arrowz** [comment]
```sh
$ unzip test-0001.zip 
Archive:  test-0001.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of test-0001.zip or
        test-0001.zip.zip, and cannot find test-0001.zip.ZIP, period.
```
Even the CLI fails to unzip it. However, you are correct that Windows can unzip this natively, and so can 7zip, so I'll look into the issue and see what the problem is.

**Comment by lutzroeder** [comment]
Can you double check the total file size of `test-0001.zip` is 655042854 bytes?

```
~/: unzip test-0001.zip 
Archive:  test-0001.zip
  inflating: test-0001        
```

The actual error seems to be bit positions getting larger than 32 bit so JavaScript `>>>` won't work.

**Comment by 101arrowz** [comment]
That's true, I should mention the limit of 512 MB on synchronous unzip. However, streaming unzip does work on larger files, so I'll see if that works for this.

**Comment by lutzroeder** [comment]
`(pos / 8) >> 0`?

**Comment by 101arrowz** [comment]
I decided against that because I was worried that the division operator followed by a bit shift would be much more expensive than a single bit shift, but as it turns out what you suggested isn't any slower. I was thinking of (and just now finished) making the synchronous operation default to synchronous streaming when files were too large, but I suppose that's not as performant as your suggestion.

**Comment by 101arrowz** [comment]
@lutzroeder I've finished making changes to support the full 4GB maximum supported by Uint8Array itself. Thanks for the suggestions, help, and debuggable examples :heart: I'll be pushing an update shortly.

**Comment by 101arrowz** [comment]
Check v0.4.4 on the NPM registry. Thanks for the bug report!

**Comment by 101arrowz** [comment]
Hey @lutzroeder, I noticed [you added a subsection of fflate into netron](https://github.com/lutzroeder/netron/commit/d64d377704b4d80f26b60ac633101ae0a175d31c). I understand that depending upon the NPM package would be difficult, since netron's build process doesn't allow for tree shaking, but I would appreciate if you could still attribute the project in the source code or README. Thanks for your interest!

**Comment by lutzroeder** [comment]
Reverted the change. The main fork is a rewrite from scratch using the reverse mapping algorithm from [UZIP.js](https://github.com/photopea/UZIP.js) and has a UZIP.js reference added to the source.

**Comment by 101arrowz** [comment]
The algorithm is actually from [SO](https://stackoverflow.com/a/60227327/10930232), you may want to cite that instead. Nothing special about the change except shift down a bit, since they're all 15 bit integers I managed to find a way to [optimize further](https://github.com/101arrowz/fflate/blob/master/src/index.ts#L51-L57). Either way, hope your rewrite works well.
