### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by mrdoob** [101arrowz/fflate#39]
**What can't you do right now?**

Recently I've been trying to generate [USDZ files](https://graphics.pixar.com/usd/docs/Usdz-File-Format-Specification.html) in JavaScript: https://github.com/mrdoob/three.js/pull/21245

The USDZ file is essentially an zip file with 0 compression that contains a 3d file and textures.

So far fflate has been great for creating the file. However, yesterday I learned that in order to produce valid USDZ files I need to make sure that the files are aligned to 64 bytes. Currently my files are invalid:

<img width="697" alt="Screen Shot 2021-02-10 at 9 05 31 PM" src="https://user-images.githubusercontent.com/97088/107572147-c0b88b00-6be3-11eb-93d6-45f3eda5fef6.png">

From the [spec](https://graphics.pixar.com/usd/docs/Usdz-File-Format-Specification.html) page:

<img width="837" alt="Screen Shot 2021-02-09 at 11 41 55 PM" src="https://user-images.githubusercontent.com/97088/107571878-67505c00-6be3-11eb-85bb-e35a8895284f.png">

I'm aware this is quite an uncommon use case, but would you be interested in adding support for this?

**Comment by 101arrowz** [comment]
Interesting, I always considered the "extra" field to be useless because literally no software (besides proprietary tools like Archive Utility) reads it. Adding support for this would not be too difficult, but you won't be able to know what length the compressed file is from `fflate`, so you can't align to a 64 byte boundary. I'll add support for this, but to solve your problem, you'll either need to disable compression or use the streaming API for low-level control and access to compressed content length. (If you'd like me to describe how exactly to do this, I'm happy to help; otherwise, I'll just publish the extra field support in a few hours.)

**Comment by 101arrowz** [comment]
@mrdoob I've published v0.6.2 to NPM, which includes support for comments and extra fields. Both of these can hold arbitrary user data, e.g. a bunch of zeros until you reach a 64 byte boundary. However, only the extra field exists in local file headers, so we need to use those. Here's some sample code to get you started:

```js
// Let's say you have a standard ZIPpable object:
const toZip = {
  'someFile': fflate.strToU8('someContent'),
  'otherStuff': fflate.strToU8('you get the point')
};

// We can mutate this object to add the padding

// Byte offset we are currently at
let offset = 0;

for (const filename in toZip) {
  const file = toZip[filename];
  // This is explained after this code block
  const headerSize = 34 + filename.length;
  offset += headerSize;

  // Bitwise AND with 63 is equivalent to mod 64
  const offsetMod64 = offset & 63;
  // If the offset is 4, after we remove the assumed
  // 4 bytes wasted in the extra field no matter what,
  // we are 0 mod 64 and don't need to add the extra
  // field to pad this file.
  if (offsetMod64 != 4) {
    // Adding this padding gets us to 0 mod 64
    const padLength = 64 - offsetMod64;
    const padding = new Uint8Array(padLength);
    toZip[filename] = [file, {
      extra: {
        // Any ID above 31 works
        12345: padding
      }
    }];
  }
  // Reset offset. Although we could add the
  // file length, since we just became 0 mod 64,
  // setting instead of adding works too.
  offset = file.length;
  
}
// Zip as normal
const uszdOutput = fflate.zipSync(toZip, { level: 0 });
```

The local header size is 30 bytes + size of the filename in UTF-8 + extra fields sizes + number of extra fields * 4. Since you have 1 extra fields and your filenames are all ASCII (presumably), this becomes 34 + length of filename + length of extra field. The above code uses that calculation to align each uncompressed file to a 64 byte boundary.

**Comment by mrdoob** [comment]
Awesome! I'll implement it right away 🙏

Hmm, I guess I need to generate a new `fflate.min.js` and `fflate.module.min.js`.

How did you generate these? I don't see scripts in this repo to generate them 🤔

https://github.com/mrdoob/three.js/issues/20941#issuecomment-752010339

**Comment by 101arrowz** [comment]
You can take a look at the CDN instructions in the README and open those URLs in the browser. [UMD](http://unpkg.com/fflate) and [ESM (use the first link that is imported)](https://cdn.skypack.dev/fflate?min)

**Comment by mrdoob** [comment]
Excellent! Many thanks! 🙏
https://github.com/mrdoob/three.js/commit/8000053e53fa3167d0d7d836808c54fd0f5f6975
