### ISSUE TITLE
Calling `inflate` on data created from `Pako.deflate` returns `(null, null)`

### ISSUE THREAD

**Issue by brianmhunt** [101arrowz/fflate#57]
Some observations that I noted:

## `inflate` fails with `(null, null)`

![image](https://user-images.githubusercontent.com/135528/117155587-e42a4680-ad8a-11eb-970c-8495322c4344.png)

## `inflateSync` fails with EOF:
![image](https://user-images.githubusercontent.com/135528/117153616-26eb1f00-ad89-11eb-8d0c-662d8f774814.png)

This is probably the most important problem since one would expect either data or an error.

## `decompress` works fine:

![image](https://user-images.githubusercontent.com/135528/117153710-3a968580-ad89-11eb-875a-cb83d828932b.png)

## `deflateSync` : incorrect header check

It appears as though Pako has a different idea of what constitutes `inflate` / `deflate` i.e.

![image](https://user-images.githubusercontent.com/135528/117154743-27d08080-ad8a-11eb-8fd7-0078c1763510.png)

## `gzipSync`: seems to correspond to `pako.inflate`

![image](https://user-images.githubusercontent.com/135528/117154819-3b7be700-ad8a-11eb-903b-b74f771d353b.png)

I noted that the builtin [`CompressionStream`](https://developer.mozilla.org/en-US/docs/Web/API/CompressionStream) seems to correlate with what Pako does i.e. `'inflate'` algorithm for Pako and CompressionStream seem to be the same.

### `zlib`: same as `gzip`
![image](https://user-images.githubusercontent.com/135528/117155272-a1686e80-ad8a-11eb-8138-2a7e2732c1bc.png)

### `zip`: fails, same as deflate

![image](https://user-images.githubusercontent.com/135528/117155368-b80ec580-ad8a-11eb-8cdd-82cbfb83ab31.png)

## Summary

I've no idea what's going on here (and the issues observed may be with Pako), but I hope the above is useful feedback.

**Comment by 101arrowz** [comment]
All intentional behavior. The names do NOT correspond 1 to 1 with Pako, because Pako named things wrong! It called Zlib "deflate", DEFLATE "deflateRaw", and GZIP "gzip".

`fflate.inflate` (and `fflate.inflateSync`) only work on data from `pako.deflateRaw`. `fflate.unzlib` (and `fflate.unzlibSync`) work on data from `pako.deflate`. `fflate.decompress` works on anything because it auto-detects header.

`pako.inflate` is like `fflate.decompress`: it works on either Zlib or GZIP header, but not raw DEFLATE.

`fflate.zipSync` is meant to create a ZIP archive, which is a different format entirely from DEFLATE (but ZIP does include DEFLATE internally). You'll need JSZip or `zip.js` or some other ZIP decompression library to handle data from `fflate.zip`/`fflate.zipSync`.

Let me know if there's anything else that confuses you.

**Comment by brianmhunt** [comment]
Thanks for the prompt reply, and great explanation.  I had a feeling it was a pako thing, but I don't have the know-how to make that call.

I think the only thing lingering is whether the `(null, null)` callback is the correct behaviour.  I'd think the API should return either an error _or_ data (or pehaps document when/why `(null, null)` can happen).

**Comment by 101arrowz** [comment]
> I think the only thing lingering is whether the (null, null) callback is the correct behaviour. I'd think the API should return either an error or data (or pehaps document when/why (null, null) can happen).

That's the thing with `fflate`. It expects you to do everything correctly, the only thing it guarantees is that the browser won't hang when you pass in a bad file. For example, none of the arguments are validated in any of the functions (e.g. for type).

In this case, however, I would expect the first parameter to be non-null. I'll investigate why exactly it's happening; thanks for letting me know.

**Comment by 101arrowz** [comment]
I found and fixed the bug; will be out in v0.7.0.

**Comment by 101arrowz** [comment]
v0.7.0 is released and this bug should be fixed, along with the improved errors from #54.
