### ISSUE TITLE
Zstandard support

### ISSUE THREAD

**Issue by fabiospampinato** [101arrowz/fflate#68]
**What can't you do right now?**

Zstandard compresses amazingly well, for my use case up to 4x better than what I can get from gzip, and it decompresses perhaps even more amazingly well. 

For my use case I kinda have to use Zstandard given its characteristics, but there doesn't seem to be a great port of Zstandard for the browser, plus I'm already using `fflate` which I find well done and pretty fast, but it just doesn't support Zstandard.

**An optimal solution**

Optimally `fflate` would add support for compressing and decompressing (although just decompressing would be enough for me, and I'd guess for most other people too) using Zstandard with a high quality and fast implementation.

**(How) is this done by other libraries?**

- [`node-zstd`](https://github.com/zwb-ict/node-zstd): it uses native bindings, a no-no for the web.
- [`node-zstandard`](https://www.npmjs.com/package/node-zstandard): it just spawns zstd as a child process.
- [`zstd-codec`](https://www.npmjs.com/package/zstd-codec): it's a 1 year out of date emscripten compiled version of zstd, which weighs almost 1MB min+gzipped and can't be tree-shaken.
- [`zstddec`](https://github.com/donmccurdy/zstddec): this seems the best port to webassembly, it only supports decoding and weighs ~17kb, but it has the following pretty concerning warning in its readme:

  > Limitations: The decoder may fail with the error wasm function signature contains illegal type when the uncompressedSize is not known in advance and given to the decode() method. This is presumably a bug in the WASM bindings, which I am not yet sure how to fix.
	  
Basically there currently isn't a great option for decoding zstd files on the web and I'd love to see one from `fflate`.

**Comment by 101arrowz** [comment]
I'm well aware of the Zstandard situation on the web. I've actually already been trying to build a Zstandard encoder/decoder in JS, but unfortunately it's a massive undertaking not only due to the higher complexity of the algorithm but also because JS simply has a speed limit. The reason `fflate` is faster than WASM Zlib is due to the high cost of data transfer to and from WASM; however, when something is complex enough, WASM's faster execution simply wins. I'm pretty sure WASM bindings will be at worst similar and at best outright better in performance than JS.

If you are looking for decent Zstd bindings, check out [these](https://github.com/evanwashere/wasm/tree/master/src/zstd). 183kB minzipped, which isn't terrible, and there's no issue with bad compression. (By the way, the author also wrote the best Zlib WASM bindings I've seen, which are [still typically slower than `fflate`](https://github.com/evanwashere/wasm/tree/master/src/zlib) and have a greater impact on bundle size).

**Comment by fabiospampinato** [comment]
Awesome! Thanks for the thorough answer and good news.

**Comment by fabiospampinato** [comment]
> I'm working on fzstd on the side and will update here when I publish the first version.

@101arrowz Could you guess at how long that will take? Like are we talking about days, weeks, months?

**Comment by 101arrowz** [comment]
Maybe 3-6 weeks, assuming nothing comes up. Since I don't have a personal need for Zstandard, I probably won't be able to stick to an exact schedule, but that's my estimation. In the meantime I recommend the Zstandard bindings I linked; they're pretty fast and are a good compromise if Zstandard compresses that much better than GZIP.
