### ISSUE TITLE
Support promises in async version

### ISSUE THREAD

**Issue by marcofugaro** [101arrowz/fflate#79]
Hey! Great library!

I am using it in the browser, and it would be great if the async versions would support promises as well instead of just callbacks. 

Ideally it would look something like this:

```js
const buffer = await fflate.zip(
  {
    'index.html': fflate.strToU8(str),
    // other files...
  },
  { level: 4 }
);
```

It looks like synchronous code but it doesn't block the main thread.

It makes sense to support promises, newer versions of node are doing so with stuff like `fs/promises` and `timers/promises`

**Comment by 101arrowz** [comment]
See #79 and [the wiki entry](https://github.com/101arrowz/fflate/wiki/FAQ#why-doesnt-fflate-use-promise-for-its-asynchronous-api) on why this isn't done. Let me know if you have further questions.

**Comment by marcofugaro** [comment]
I see, supporting old browsers while keeping a small filesize is hard.

Have you thought about doing an old-browser specific version so that people that need to support IE11 can use that? For example:

```js
<script src="https://cdn.jsdelivr.net/npm/fflate/umd/index.ie11.js"></script>
```

It would either use no promise or use this [1kb promise polyfill](https://github.com/taylorhakes/promise-polyfill)?

**Comment by 101arrowz** [comment]
I have thought of using a separate build for IE11. I write ESNext for all of my personal projects and make heavy use of `Promise`; usually I don't try to support IE11 as it's a dead browser, but when I do I use the polyfill you linked for `Promise`. The problem for a project like this is that the entire package is designed to be lower-level and to support ancient engines, so adding one component of new JS is incongruous. I've also been asked to add support for WHATWG streams in the streaming APIs, but those are even more recent and even more unsupported than `Promise`.

As support for features of new JS is such a popular feature request, I'll create a wrapper for `fflate` that supports the modern features you want. See #80 for more info.

**Comment by marcofugaro** [comment]
Understood, thanks for the explaination and the great work you did for this library, it's really performant! 💪

Should I leave this issue open for future users who might request this feature?

**Comment by 101arrowz** [comment]
Future users can just search the issues tab for "Promise" and they'll find it. Thanks for the feature request!

**Comment by appsforartists** [comment]
#80 is a dead link.  I'm guessing it evolved to https://github.com/101arrowz/fflate/wiki/Guide:-Modern-(Buildless)?

FWIW, I'm investigating zip libraries now, and I'm leaning towards https://github.com/Touffy/client-zip because it has a modern API.  I respect your hesitation to break old browsers, but agree with other commenters that I don't see why releasing a modern version would break people who are already happy with the old one.  Requirements to support legacy systems has been a major reason to stop taking upgrades for as along as software has existed.

Seems like you could even do something like this:

```typescript
const zipToPromise = (files: AsyncZippable, options: AsyncZipOptions = {}) => {
  if (!('Promise' in window)) {
    throw new Error('zipToPromise requires promises.  Use `zip` to support older browsers.');
  }

  return new Promise(
    (resolve, reject) => zip(
      files,
      options,
      (error, result) => {
        if (error) {
          reject(error);
        } else {
          resolve(result);
        }
      }
    )
  );
}

// repeat for other modern APIs
```

to keep with the times without breaking the build if someone imports a new version in an old browser.

**Comment by 101arrowz** [comment]
I have to agree, `fflate`'s API (especially the streams) do feel a bit dated today. I'm not sure where #80 went to be honest, but it was an issue tracking a potential new package wrapping `fflate` with an evergreen API, WHATWG streams, thenables for async operations, `AbortController`, etc. I haven't had time to actually create that package and at this point I think there are better alternatives anyway.

I still hesitate to make `fflate` itself modern because it's really meant to be a super-fast, pure JS DEFLATE implementation and not much more - the vast majority of current dependents don't need or want a fancy new API (in fact, the most commonly used functions are `zipSync`/`unzipSync` and `gzipSync`/`gunzipSync`).

For the time being, I don't have a good solution for you. If you want a modern API and have no need for compression support, `client-zip` is definitely a better choice than `fflate`. I've actually spoken with the maintainer of that package before - it's probably the best package available for that specific use case. Alternatively I can recommend [`@zip.js/zip.js`](https://gildas-lormeau.github.io/zip.js/) if you need extra features.

**Comment by mk-pmb** [comment]
I'm not sure I fully understand the approach here: Is it just about promisifying the sync version of fflate? Then how do I get a promised version of the asynchronous mode? (Because I want the 3x speed boost claimed in the readme.)

Edit: Or is it just about the file size for browsers? Could we then maybe have `require('fflate/promising')` as a stopgap for node.js?
