### ISSUE TITLE
LZ4 Support

### ISSUE THREAD

**Issue by yovanoc** [101arrowz/fflate#89]
Hello, I think adding http://lz4.github.io/lz4/ support could be very useful.

Even more with stream feature if possible

**Comment by 101arrowz** [comment]
Most of the "fast" compression algorithms (LZ4, Zstandard, etc.) are much slower for compression in JS than in WASM because JS doesn't support 32 bit unsigned integers, and because there's no potential for vectorization. The fact that Zlib can't traditionally be vectorized and is more focused on compression ratio than speed is the reason `fflate` is faster than Zlib ports to WASM.

Therefore I recommend using [`lz4-wasm`](https://github.com/PSeitz/lz4_flex/tree/master/lz4-wasm). Since it doesn't support streaming you might need to rewrite the Rust `wasm-bindgen` glue a bit, but it shouldn't be too difficult.

By the way, if you just need decompression and are looking for a faster format, try [`fzstd`](https://github.com/101arrowz/fzstd). Let me know if you have any questions.
